In [1]:
import sys
import importlib as il
import numpy as np
from ase.io import read
from ase.geometry import wrap_positions
from hilde.settings import Settings
import hilde.phonopy.wrapper as ph
from hilde.helpers.supercell import make_supercell

sys.path.insert(0, "/home/knoop/local/hilde")

lp = il.import_module('hilde.helpers.supercell.lattice_points')

In [2]:
settings = Settings()
smatrix = np.array(settings.phonopy.supercell_matrix)
print(smatrix)

primitive = read('geometry.in', format='aims')

ase_scell = make_supercell(primitive, smatrix)
ase_scell.write('geometry.in.supercell', format='aims')

_, pho_scell, _ = ph.preprocess(primitive, smatrix.T)
pho_scell.write('geometry.in.supercell.phonopy', format='aims')

[[2 0 0]
 [1 1 0]
 [0 0 1]]


In [3]:
primitive.positions, ase_scell.positions

(array([[-1.64496200e-10,  1.84339054e+00,  4.24710027e-04],
        [ 1.59642304e+00,  9.21695271e-01,  2.60268079e+00],
        [-1.64496200e-10,  1.84339054e+00,  1.95979300e+00],
        [ 1.59642304e+00,  9.21695271e-01,  4.56204908e+00]]),
 array([[1.59642304e+00, 9.21695271e-01, 2.60268079e+00],
        [1.59642304e+00, 9.21695271e-01, 4.56204908e+00],
        [3.19284608e+00, 1.84339054e+00, 4.24710027e-04],
        [4.78926911e+00, 9.21695270e-01, 2.60268079e+00],
        [3.19284608e+00, 1.84339054e+00, 1.95979300e+00],
        [4.78926911e+00, 9.21695270e-01, 4.56204908e+00],
        [6.38569215e+00, 1.84339054e+00, 4.24710027e-04],
        [6.38569215e+00, 1.84339054e+00, 1.95979300e+00]]))

In [4]:
il.reload(lp)
assign_primitive_positions = lp.assign_primitive_positions

indices = assign_primitive_positions(primitive, ase_scell)

for ii, pos in enumerate(primitive.positions):
    print(' '.join((f'{el:-10.5f}' for el in pos)), ii)

for pos, idx in zip(ase_scell.positions, indices):
    print(' '.join((f'{el:-10.5f}' for el in pos)), idx)

  -0.00000    1.84339    0.00042 0
   1.59642    0.92170    2.60268 1
  -0.00000    1.84339    1.95979 2
   1.59642    0.92170    4.56205 3
   1.59642    0.92170    2.60268 (1, 0)
   1.59642    0.92170    4.56205 (3, 0)
   3.19285    1.84339    0.00042 (0, 1)
   4.78927    0.92170    2.60268 (1, 1)
   3.19285    1.84339    1.95979 (2, 1)
   4.78927    0.92170    4.56205 (3, 1)
   6.38569    1.84339    0.00042 (0, 0)
   6.38569    1.84339    1.95979 (2, 0)


In [5]:
indices = assign_primitive_positions(primitive, pho_scell)

for ii, pos in enumerate(primitive.positions):
    print(' '.join((f'{el:-10.5f}' for el in pos)), ii)

for pos, idx in zip(ase_scell.positions, indices):
    print(' '.join((f'{el:-10.5f}' for el in pos)), idx)

  -0.00000    1.84339    0.00042 0
   1.59642    0.92170    2.60268 1
  -0.00000    1.84339    1.95979 2
   1.59642    0.92170    4.56205 3
   1.59642    0.92170    2.60268 (0, 1)
   1.59642    0.92170    4.56205 (1, 0)
   3.19285    1.84339    0.00042 (1, 1)
   4.78927    0.92170    2.60268 (2, 1)
   3.19285    1.84339    1.95979 (3, 0)
   4.78927    0.92170    4.56205 (3, 1)
   6.38569    1.84339    0.00042 (0, 0)
   6.38569    1.84339    1.95979 (2, 0)
