# Supercell Conventions
To generate the supercell lattice from a given primitive lattice $L_\text{P}$ and a supercell matrix $S$, we typically perform
$$ L_\text{S} = S \cdot L_\text{P}~. $$
Here we show which conventions have to be used to build the correct supercells from given supercell matrices.

In [1]:
import numpy as np
from hilde.parsers import read_aims
from hilde.helpers.supercell import find_cubic_cell
from hilde.helpers.geometry import get_cubicness
from hilde.helpers.maths import clean_matrix
from ase.build.supercells import make_supercell
from hilde.phonopy import phono as ph

In [2]:
atoms = read_aims('gan.in')

In [3]:
n_target = 10
target_size = n_target / len(atoms)

In [4]:
smatrix = find_cubic_cell(cell=atoms.cell, target_size=target_size)
print(smatrix)
print(atoms.cell @ smatrix)
print(get_cubicness(atoms.cell @ smatrix))
print(clean_matrix(smatrix @ atoms.cell, eps=1e-8))
print(get_cubicness(smatrix @ atoms.cell))

[[ 1 -1  0]
 [ 1  2  0]
 [ 0  0  1]]
[[ 3.19141392 -3.19141392  0.        ]
 [ 1.16813857  7.12339802  0.        ]
 [ 0.          0.          5.20200469]]
0.709968439548574
[[ 4.78712088 -2.76384553  0.        ]
 [ 0.          5.52769106  0.        ]
 [ 0.          0.          5.20200469]]
0.9271388123614653


### ASE
To implement $$S \cdot L$$ when building the supercell with **ase.build**, we give $$S$$
to `make_supercell(atoms, smatrix)`

In [5]:
clean_matrix(make_supercell(atoms, smatrix).cell, eps=1e-8)

array([[ 4.78712088, -2.76384553,  0.        ],
       [ 0.        ,  5.52769106,  0.        ],
       [ 0.        ,  0.        ,  5.20200469]])

### Phonopy
To implement $$S \cdot L$$ when building the supercell with **phonopy**, we need to provide $$S^{\mathrm t}~,$$
i.e., `smatrix.T`

In [6]:
phonon, sc, scs = ph.preprocess(atoms, smatrix.T)
clean_matrix(sc.cell, eps=1e-8)

array([[ 4.78712088, -2.76384553,  0.        ],
       [ 0.        ,  5.52769106,  0.        ],
       [ 0.        ,  0.        ,  5.20200469]])